cmake_minimum_required(VERSION 3.8)
project(pinchot)

add_library(${CMAKE_PROJECT_NAME} SHARED)

set(PINCHOT_API_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR})
list(APPEND CMAKE_MODULE_PATH ${PINCHOT_API_ROOT_DIR})
include(PinchotBuildLibrary)

include(GNUInstallDirs)
install(TARGETS ${CMAKE_PROJECT_NAME}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
install(FILES ${SRC_DIR}/joescan_pinchot.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
